version: "3"
services:
  frontend:
    container_name: abw-bs-fe
    restart: always
    build: frontend/
    environment:
      - API_URL=${API_URL}
      - SUBFOLDER=${SUBFOLDER}
    ports:
      - '127.0.0.1:6969:80'
    networks:
      - abwms
 
  backend:
    container_name: abw-bs-be
    restart: always
    build: backend/
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - FIRST_USER=${FIRST_USER}
      - FIRST_USER_PASSWORD=${FIRST_USER_PASSWORD}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
    ports:
      - "127.0.0.1:42069:42069"
    networks:
      - abwms
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    build: .
    restart: always
    environment:
        - MONGO_INITDB_DATABASE=${MONGO_DB}
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - abwms
    volumes:
      - mongo-data:/data/db
 
networks:
  abwms:
    driver: bridge

volumes:
  mongo-data:
    driver: local
