version: "3"
services:
  frontend:
    container_name: abw-bs-fe
    restart: always
    environment:
      - HTTP_PROXY=${PROXY_SERVER}
      - HTTPS_PROXY=${PROXY_SERVER}
    build:
      context: frontend/
      args:
        - API_URL=${API_URL}
        - SUBFOLDER=${SUBFOLDER}
        - HTTP_PROXY=${PROXY_SERVER}
        - HTTPS_PROXY=${PROXY_SERVER}
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - abwms
 
  backend:
    container_name: abw-bs-be
    restart: always
    build: backend/
    args:
      - HTTP_PROXY=${PROXY_SERVER}
      - HTTPS_PROXY=${PROXY_SERVER}
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - FIRST_USER=${FIRST_USER}
      - FIRST_USER_PASSWORD=${FIRST_USER_PASSWORD}
      - HTTP_PROXY=${PROXY_SERVER}
      - HTTPS_PROXY=${PROXY_SERVER}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
    ports:
      - "${API_PORT}:80"
    networks:
      - abwms
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    build: .
    restart: always
    environment:
        - MONGO_INITDB_DATABASE=${MONGO_DB}
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - abwms
    volumes:
      - mongo-data:/data/db
 
networks:
  abwms:
    driver: bridge

volumes:
  mongo-data:
    driver: local
