version: "3"
services:
  frontend:
    container_name: abw-bs-fe
    restart: always
    build: ./frontend/
    env_file:
      - local.frontend.env
    ports:
      - '127.0.0.1:6969:80'
    networks:
      - abwms
 
  backend:
    container_name: abw-bs-be
    restart: always
    build: ./backend/
    env_file:
      - local.backend.env
    ports:
      - "127.0.0.1:42069:42069"
    networks:
      - abwms
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    build: .
    restart: always
    env_file:
      - local.backend.env
    environment:
        - MONGO_INITDB_DATABASE=${MONGO_DB}
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - abwms
    volumes:
      - mongo-data:/data/db
 
networks:
  abwms:
    driver: bridge

volumes:
  mongo-data:
    driver: local
